services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: postgres
      POSTGRES_DB: agrixdb

#  mysql:
#    container_name: agrix-db
#    image: mysql:8.0.32
#    restart: always
#    ports:
#      - 3308:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: agrixdb